UTF16 and Conhost support for Windows
hpjansson/chafa pull request #175
Opened 2023-11-04 19:14 UTC by oshaboy

this adds 2 new options
`--utf16` output using WriteConsoleW 
`--format conhost` use Legacy Windows Console API (implies --utf16)

2023-11-04 19:17 UTC, oshaboy commented
Oh right there's also `--encoding` which converts utf-8 to a legacy codepage using iconv

2023-11-10 02:12 UTC, hpjansson requested changes
This looks pretty good overall. My main requests are that we leave the UTF-16 switch/`WriteConsoleW()` code out for now and focus on the direct Conhost output, plus a raft of small stylistic changes.

Thanks a lot for doing this!

2023-11-10 02:12 UTC, hpjansson commented on tools/chafa/chafa.c
> +#endif
GNU style and some spacing. Opening and closing braces `{` and `}` each on its own line, blank line between variable decls and following code. `ConhostRow * lines` should be `ConhostRow *lines`. Spaces around `=`.

2023-11-10 02:12 UTC, hpjansson commented on tools/chafa/chafa.c
> +
No blank line here.

2023-11-10 02:12 UTC, hpjansson commented on tools/chafa/conhost.c
Please go over this file and update the style according to my earlier comments. I don't want to pepper it with nitpicks :-) The most important bit is to use GNU style instead of K&R, and to use no more than a single blank line for spacing (there's a place where you have three).

Feel free to add a copyright header analogous to the other files in the project. The license should be same. You retain the copyright, so add your own name if you want to.

2023-11-10 02:12 UTC, hpjansson commented on tools/chafa/chafa.c
> -#endif
I guess if we're saving the UTF-16 stuff for later, all you need is `canvas_to_conhost` for output, so this block doesn't need to be moved, and you can drop `safe_WriteConsoleW` too (or `#if 0` it out so we can use it when UTF-16 becomes independently selectable).

2023-11-11 00:25 UTC, merged